on: push
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
      - name: generate
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA nixpkgs.hugo
          nix-env -if https://fluidattacks.com/makes/install/21.11

          sudo rm -rf /data
          sudo mkdir /data
          sudo chown $USER /data
          git clone --depth 1 https://github.com/on-nix/pkgs /data/github/on-nix/pkgs
          m . /generate/data
          hugo
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          author: Kevin Amado <kamadorueda@gmail.com>
          committer: Kevin Amado <kamadorueda@gmail.com>
          commit_message: "feat(doc): build and release website"

          build_dir: docs
          fqdn: pkgs.on-nix.com
          keep_history: false
          target_branch: release
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
